version: '3'

services:
  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=toorPass
      - MYSQL_DATABASE=defaultBase
      - MYSQL_USER=root
      - MYSQL_PASSWORD=toor
    volumes:
      - ./data/:/var/lib/mysql
    expose:
      - "3306"

  adminer:
    image: adminer
    ports:
      - 8081:8080
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    links:
      - "mariadb:database"

  fpm:
    image: php:7-fpm