version: '3.1'

services:
  db:
    image: mariadb:10.5
    environment:
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=first_bdd
    volumes:
      - ./data:/var/lib/mysql
  front:
    image: adminer
    ports:
      - 8080:8080

