version: '3.1'

services:
  db:
    image: mariadb:10.5
    environment:
      - MYSQL_USER=david
      - MYSQL_PASSWORD=pictime
      - MYSQL_ROOT_PASSWORD=supermotdepasse
      - MYSQL_DATABASE=formation
    volumes:
      - ./data:/var/lib/mysql
  front:
    image: adminer
    ports:
      - 8080:8080
