version: '3.1'

services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=supermotdepasse
      - MYSQL_DATABASE=DockerDB
    volumes:
      - ./data:/var/lib/mysql
  front:
    image: adminer
    restart: always
    ports:
      - 8080:8080

